### ISSUE TITLE
There isn't an image called "hangman_steps/6.png"

### ISSUE THREAD

**Issue by p3ddd** [ftde0/ftde0.github.io#1]
There isn't an image called "hangman_steps/6.png"

**Comment by ftde0** [comment]
Hi,
There is no 6.png. The hangman game should stop at 5.png when a player has lost.

Is there a scenario where it tries to fetch 6.png?

**Comment by p3ddd** [comment]
I see. I think it's because the lose function has a delay.

If I click faster, it will even try to fetch 8.png.

**Comment by ftde0** [comment]
Thanks for bringing this up, I got this fixed along with a different minor bug.
